Repository gridhead/metasource, pull requests merged in 2025-07, with the labels that each got.

#67 Write functionality tests with relatively appreciative coverage
  Makefile
  main.go
  metasource/config/base.go
  metasource/driver/cont.go
  metasource/driver/fish.go
  metasource/driver/meta.go
  metasource/driver/popu.go
  metasource/driver/proc.go
  metasource/driver/pull.go
  metasource/driver/util.go
  metasource/lookup/brch.go
  metasource/lookup/coop.go
  metasource/lookup/file.go
  metasource/lookup/othr.go
  metasource/lookup/plus.go
  metasource/lookup/prmy.go
  metasource/lookup/rela.go
  metasource/lookup/srce.go
  metasource/option/database.go
  metasource/option/dispense.go
  metasource/reader/plus.go
  metasource/routes/brch.go
  metasource/routes/file.go
  metasource/routes/home.go
  metasource/routes/othr.go
  metasource/routes/prmy.go
  metasource/routes/rela.go
  metasource/routes/srce.go
  metasource/routes/stat.go
  test/assets/testbase_filelists.sqlite
  test/assets/testbase_filelists.xml
  test/assets/testbase_other.sqlite
  test/assets/testbase_other.xml
  test/assets/testbase_primary.sqlite
  test/assets/testbase_primary.xml
  test/base.go
  test/config_base_test.go
  test/driver_cont_test.go
  test/driver_fish_test.go
  test/driver_hash_test.go
  test/driver_main_test.go
  test/driver_proc_test.go
  test/driver_pull_test.go
  test/lookup_brch_test.go
  test/lookup_coop_test.go
  test/lookup_file_test.go
  test/lookup_othr_test.go
  test/lookup_plus_test.go
  test/lookup_prmy_test.go
  test/lookup_rela_test.go
  test/lookup_srce_test.go
  test/reader_plus_test.go
  test/routes_brch_test.go
  test/routes_file_test.go
  test/routes_home_test.go
  test/routes_othr_test.go
  test/routes_prmy_test.go
  test/routes_rela_test.go
  test/routes_srce_test.go
  test/routes_stat_test.go
Labels: quality

#47 Arrange for publishing the project as a container image #41
  Containerfile
  Makefile
  README.md
Labels: good first issue

#73 Mark the archived status on the documentation
  README.md
Labels: documentation
