Repository gridhead/metasource, pull requests merged in 2025-05, with the labels that each got.

#64 Resolve the linting issue marked out by the continuous integration quality checks
  .github/workflows/qlty.yml
  main.go
  metasource/driver/fish.go
  metasource/driver/hash.go
  metasource/driver/main.go
  metasource/driver/popu.go
  metasource/driver/proc.go
  metasource/driver/pull.go
  metasource/driver/rsrc.go
  metasource/driver/util.go
  metasource/lookup/file.go
  metasource/lookup/othr.go
  metasource/lookup/prmy.go
  metasource/lookup/rela.go
  metasource/lookup/srce.go
  metasource/models/home/base.go
  metasource/reader/file.go
  metasource/reader/othr.go
  metasource/reader/plus.go
  metasource/reader/prmy.go
  metasource/routes/othr.go
  metasource/routes/prmy.go
  metasource/routes/rela.go
  metasource/routes/srce.go
Labels: bug

#66 Introduce an interactive interface for operating endpoints
  go.mod
  go.sum
  main.go
  metasource/models/page/base.go
  metasource/routes/assets/bs.css
  metasource/routes/assets/bs.js
  metasource/routes/assets/core.css
  metasource/routes/assets/core.js
  metasource/routes/assets/mono_bdit.ttf
  metasource/routes/assets/mono_bold.ttf
  metasource/routes/assets/mono_rlar.ttf
  metasource/routes/assets/mono_rlit.ttf
  metasource/routes/assets/sans_bdit.ttf
  metasource/routes/assets/sans_bold.ttf
  metasource/routes/assets/sans_rlar.ttf
  metasource/routes/assets/sans_rlit.ttf
  metasource/routes/home.go
  metasource/routes/home.html
  metasource/routes/shapes/home.html
  metasource/routes/stat.go
Labels: enhancement

#69 chore: updated doc with description of metasource
  README.md
Labels: documentation
