Repository gridhead/metasource, pull requests merged in 2025-04, with the labels that each got.

#26 Avoid early loop return on instance failure
  metasource/driver/main.go
Labels: bug

#27 Include lookup and service endpoint for branches
  main.go
  metasource/lookup/brch.go
  metasource/routes/brch.go
Labels: enhancement

#34 Cleanup the deprecated XML-based lookup codebase
  metasource/models/rels/base.go
  metasource/models/sxml/file.go
  metasource/models/sxml/misc.go
  metasource/models/sxml/othr.go
  metasource/models/sxml/prmy.go
  metasource/runner/file.go
  metasource/runner/othr.go
  metasource/runner/plus.go
  metasource/runner/prmy.go
Labels: bug

#35 Introduce CORS support for various services
  go.mod
  go.sum
  main.go
Labels: enhancement

#36 Create a homepage with the documentation of possible endpoints
  main.go
  metasource/routes/home.go
  metasource/routes/home.html
Labels: enhancement

#38 Throw a `404 Not Found` error when the requested package was not found
  main.go
  metasource/lookup/coop.go
  metasource/lookup/file.go
  metasource/lookup/othr.go
  metasource/lookup/plus.go
  metasource/lookup/prmy.go
  metasource/lookup/rela.go
  metasource/lookup/srce.go
  metasource/routes/file.go
  metasource/routes/othr.go
  metasource/routes/prmy.go
  metasource/routes/rela.go
  metasource/routes/srce.go
Labels: bug

#40 Provide functional documentation for the consumers and developers
  README.md
Labels: documentation

#44 Include source RPM name matching using regular expression
  metasource/lookup/srce.go
Labels: bug

#49 Strip the trailing slash (`/`) and continue routing
  main.go
Labels: bug

#52 Add custom port option while starting the service
  main.go
Labels: enhancement

#48 Fix dependency requirement and version compatibility
  README.md
  go.mod
Labels: documentation

#54 Download to a random temporary directory and perform moving on completion
  README.md
  main.go
  metasource/config/base.go
  metasource/driver/fish.go
  metasource/driver/main.go
  metasource/driver/proc.go
  metasource/driver/pull.go
  metasource/driver/rand.go
  metasource/driver/util.go
Labels: enhancement

#57 Add continuous integration routines for codebase quality
  .github/workflows/qlty.yml
  metasource/driver/rand.go
  metasource/driver/util.go
Labels: quality

#58 Amend the continuous integration stages
  .github/workflows/qlty.yml
Labels: quality
